"""
Dynamic persona-boundary response builder (spec Part 8/9).

This is DELIBERATELY template-based, not another LLM call. If the
boundary-refusal text itself were generated by an LLM given the
user's request as context, there would be a real (if small) risk of
the model partially answering before or after refusing — exactly the
failure mode the spec calls out as unacceptable ("here's the
recipe... however, I'm currently a Teacher"). A deterministic
template built ONLY from the persona's own configured fields
(`persona.name`, `persona.identity`, `persona.scope`) cannot leak
substantive content about the user's actual request, because it never
sees the user's request as generation context — it only receives the
already-decided classification result (requested_domain,
requested_persona_or_role) as short labels to slot in.

Suggestion logic (Part 9) is genuinely dynamic — it works from
whatever personas exist in the database (`available_personas`), not
a hardcoded list, and only suggests when there's a real match, per
"do not randomly suggest personas."
"""
from app.drift.intent_classifier import IntentClassification
from app.models.persona import Persona


def _persona_purpose_clause(persona: Persona) -> str:
    """Builds "My role is to <purpose>" from whatever the persona actually has
    configured — falls back gracefully through description -> identity ->
    scope -> a generic clause if none are set, since not every persona in the
    database is guaranteed to have every field filled in."""
    if persona.description:
        return persona.description.rstrip(".")
    if persona.scope:
        return f"help with {persona.scope.rstrip('.')}"
    if persona.identity:
        return persona.identity.rstrip(".")
    return f"operate as {persona.name}"


import re


def _find_matching_personas(available_personas: list[Persona], requested_domain: str, requested_persona_or_role: str | None) -> list[Persona]:
    """Suggests OTHER configured personas whose name or scope text plausibly
    matches what the user actually wants — a real (if simple) text-overlap
    check against real persona data, not a hardcoded mapping."""
    if not available_personas:
        return []
    needle_parts = [p.lower() for p in [requested_domain, requested_persona_or_role] if p]
    if not needle_parts:
        return []

    def _words(text: str) -> set[str]:
        return {w for w in re.findall(r"[a-z]+", text.lower()) if len(w) > 3}

    matches = []
    for candidate in available_personas:
        haystack = f"{candidate.name} {candidate.scope} {candidate.identity} {candidate.description}".lower()
        if any(part and part in haystack for part in needle_parts):
            matches.append(candidate)
            continue
        needle_words = {w for part in needle_parts for w in _words(part)}
        if needle_words & _words(haystack):
            matches.append(candidate)
    return matches[:2]  # don't overwhelm the refusal with a long list


def build_boundary_response(
    persona: Persona,
    classification: IntentClassification,
    available_personas: list[Persona] | None = None,
) -> str:
    """The single source of truth for boundary-refusal wording (spec Part 8:
    "reusable mechanism ... generated dynamically from the persona
    configuration", not one hardcoded string per persona name)."""
    purpose = _persona_purpose_clause(persona)

    if classification.persona_switch_attempt and classification.requested_persona_or_role:
        opening = (
            f"Sorry, I can't do that because I am currently assigned as {persona.name}. "
            f"I'm designed to {purpose}, not to act as {classification.requested_persona_or_role}."
        )
    elif classification.persona_switch_attempt:
        opening = (
            f"Sorry, I can't take on a different role because I am currently assigned as {persona.name}. "
            f"I'm designed to {purpose}."
        )
    else:
        opening = (
            f"Sorry, I can't help with that request because I am currently assigned as {persona.name}. "
            f"I'm designed to {purpose}."
        )

    suggestions = _find_matching_personas(available_personas or [], classification.requested_domain, classification.requested_persona_or_role)
    if suggestions:
        names = " or ".join(p.name for p in suggestions)
        closing = f" Please select {names} for this request, if available."
    else:
        closing = " Please select a more appropriate persona for this request."

    return opening + closing
